TareaProgra1/Controllers/ArticuloEntitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TareaProgra1.Data;
using TareaProgra1.Models;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data;
using System.Diagnostics;
using System.Xml;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;

namespace TareaProgra1.Controllers
    
{
    //[Authorize]
    public class ArticuloEntitiesController : Controller
    {
        private readonly BDContext _context;

        public ArticuloEntitiesController(BDContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> salir()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login", "Cuenta");

        }

        // GET: ArticuloEntities
        public async Task<IActionResult> Index()
        {
            string xmlFilePath = "datos.xml";
            string connectionString = "Server=databasetarea1.ccdblu414uis.us-east-1.rds.amazonaws.com,1433;Database=Tarea2BDI;User ID=admin;Password=bases5181;TrustServerCertificate=true";
            //LEER CLASE ARTICULO
            try
            {
                XmlDocument xmlDoc = new XmlDocument();
                xmlDoc.Load(xmlFilePath);

                XmlNodeList claseArticulosXML = xmlDoc.SelectNodes("/root/ClasesdeArticulos/ClasedeArticulos");

                foreach (XmlNode clase in claseArticulosXML)
                {
                    string nombreClaseArticulos = clase.Attributes["Nombre"].Value;

                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        connection.Open();
                        using (SqlCommand command = new SqlCommand("InsertarClaseArticulo", connection))
                        {
                            command.CommandType = System.Data.CommandType.StoredProcedure;
                            command.Parameters.Add("@Nombre", SqlDbType.VarChar, 128).Value = nombreClaseArticulos;
                            command.ExecuteNonQuery();
                        }
                        connection.Close();
                    }
                }

            }
            catch (Exception ex)
            {
                Debug.WriteLine("ERROR al leer el earchivo XML: " + ex.Message);
            }

            //LEER ARTICULOS
            try
            {
                XmlDocument xmlDoc = new XmlDocument();
                xmlDoc.Load(xmlFilePath);

                XmlNodeList claseArticulosXML = xmlDoc.SelectNodes("/root/Articulos/Articulo");

                foreach (XmlNode clase in claseArticulosXML)
                {

                    string codigoArticulo = clase.Attributes["Codigo"].Value;
                    string nombreArticulo = clase.Attributes["Nombre"].Value;
                    string precioString = clase.Attributes["Precio"].Value;
                    decimal precioArticulo = 0;
                    try
                    {
                        precioArticulo = decimal.Parse(precioString);
                        Console.WriteLine("Conversión a: " + precioArticulo);
                    }
                    catch (FormatException ex)
                    {
                        Console.WriteLine("ERROR " + ex.Message);
                    }
                    string nombreClaseArticulo = clase.Attributes["ClasedeArticulos"].Value;
                    int idClaseArticulo;
                    bool activo = true;
                    using (SqlConnection connection = new SqlConnection(connectionString))
                    {
                        connection.Open();
                        using (SqlCommand command = new SqlCommand("GetIdClassArticleByName", connection))
                        {
                            command.CommandType = System.Data.CommandType.StoredProcedure;
                            command.Parameters.Add("@Nombre", SqlDbType.VarChar, 128).Value = nombreClaseArticulo;

                            SqlParameter parametroResultado = new SqlParameter("@Resultado", SqlDbType.Int);
                            parametroResultado.Direction = ParameterDirection.Output;
                            command.Parameters.Add(parametroResultado);

                            command.ExecuteNonQuery();

                            idClaseArticulo = (int)parametroResultado.Value;
                        }
                        using (SqlCommand command2 = new SqlCommand("InsertarArticulo", connection))
                        {
                            command2.CommandType = System.Data.CommandType.StoredProcedure;
                            command2.Parameters.Add("@Nombre", SqlDbType.VarChar, 128).Value = nombreArticulo;
                            command2.Parameters.Add("@Codigo", SqlDbType.VarChar, 32).Value = codigoArticulo;
                            command2.Parameters.Add("@idClaseArticulo", SqlDbType.Int).Value = idClaseArticulo;
                            command2.Parameters.Add("@Precio", SqlDbType.Money).Value = precioArticulo;
                            command2.Parameters.Add("@EsActivo", SqlDbType.Bit).Value = activo;

                            command2.ExecuteNonQuery();
                        }
                        connection.Close();
                    }
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine("ERROR al leer el earchivo XML: " + ex.Message);
            }

            var articulosOrdenados = await _context.Articulo.FromSqlRaw("EXEC GetAllArticles").ToListAsync();
            var claseArticulos = await _context.ClaseArticulo.FromSqlRaw("EXEC GetAllClassArticles").ToListAsync();

            var vistaLista = new List<Tablas>();

            foreach (var articulo in articulosOrdenados)
            {
                var vistaModel = new Tablas
                {
                    Id = articulo.Id,
                    Codigo = articulo.Codigo,
                    Nombre = articulo.Nombre,
                    IdClaseArticulo = articulo.IdClaseArticulo,
                    Precio = articulo.Precio,
                    EsActivo = articulo.EsActivo,
                    NombreClaseArticulo = claseArticulos.FirstOrDefault(ca => ca.Id == articulo.IdClaseArticulo)?.Nombre
                };
                vistaLista.Add(vistaModel);
            }

            ViewBag.claseArticulo = claseArticulos;
            return _context.Articulo != null ?
                        View(vistaLista) :
                        Problem("Entity set 'BDContext.Articulo'  is null.");
        }

        // GET: ArticuloEntities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Articulo == null)
            {
                return NotFound();
            }

            var articuloEntity = await _context.Articulo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (articuloEntity == null)
            {
                return NotFound();
            }

            return View(articuloEntity);
        }

        // GET: ArticuloEntities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ArticuloEntities/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Codigo,Nombre,IdClaseArticulo,Precio,EsActivo")] ArticuloEntity articuloEntity)
        {
            if (ModelState.IsValid)
            {
                SqlConnection conn = (SqlConnection)_context.Database.GetDbConnection();
                SqlCommand cmd = conn.CreateCommand();
                conn.Open();

                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "InsertarArticulo";
               // cmd.Parameters.Add("@id", System.Data.SqlDbType.Int).Value = articuloEntity.Id;
                cmd.Parameters.Add("@Codigo", System.Data.SqlDbType.VarChar, 32).Value = articuloEntity.Codigo;
                cmd.Parameters.Add("@Nombre", System.Data.SqlDbType.VarChar, 128).Value = articuloEntity.Nombre;
                cmd.Parameters.Add("@idClaseArticulo", System.Data.SqlDbType.Int).Value = articuloEntity.IdClaseArticulo;
                //cmd.Parameters.Add("@nombreClaseArticulo", System.Data.SqlDbType.VarChar, 128).Value = articuloEntity.NombreClaseArticulo;
                cmd.Parameters.Add("@Precio", System.Data.SqlDbType.Decimal).Value = articuloEntity.Precio;
                cmd.Parameters.Add("@EsActivo", System.Data.SqlDbType.Bit).Value = articuloEntity.EsActivo;
                cmd.ExecuteNonQuery();

                conn.Close(); 
               // _context.Add(articuloEntity);
                //await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(articuloEntity);
        }

        // GET: ArticuloEntities/Edit/5
        
        public async Task<IActionResult> Edit(int? Id)
        {
            var articulosOrdenados = await _context.Articulo.FromSqlRaw("EXEC GetAllArticles").ToListAsync();
            var claseArticulos = await _context.ClaseArticulo.FromSqlRaw("EXEC GetAllClassArticles").ToListAsync();

            var vistaLista = new List<Tablas>();

            ViewBag.ArticuloId = Id;

            foreach (var articulo in articulosOrdenados)
            {

TareaProgra1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TareaProgra1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TareaProgra1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TareaProgra1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Salir">Cerrar Sesion</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ArticuloEntities" asp-action="Index">Articulos</a>
                        </li>
                        

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TareaProgra1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>